-- Ejecuta todo este archivo en el SQL Editor de Supabase.

create table if not exists public.gallery_photos (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 60),
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.gallery_photos enable row level security;

revoke all on table public.gallery_photos from anon, authenticated;
grant select on table public.gallery_photos to anon, authenticated;
grant insert on table public.gallery_photos to authenticated;
revoke all on sequence public.gallery_photos_id_seq from anon;
grant usage, select on sequence public.gallery_photos_id_seq to authenticated;

drop policy if exists "Galeria visible para todos" on public.gallery_photos;
create policy "Galeria visible para todos"
on public.gallery_photos for select
to anon, authenticated
using (true);

drop policy if exists "Cualquiera puede agregar recuerdos" on public.gallery_photos;
drop policy if exists "Solo admin puede agregar recuerdos" on public.gallery_photos;
create policy "Solo admin puede agregar recuerdos"
on public.gallery_photos for insert
to authenticated
with check (
  char_length(title) between 1 and 60
  and storage_path ~ '^[0-9]+-[0-9a-f-]+\.(jpg|jpeg|png|webp)$'
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gallery',
  'gallery',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Fotos de galeria publicas" on storage.objects;
create policy "Fotos de galeria publicas"
on storage.objects for select
to public
using (bucket_id = 'gallery');

drop policy if exists "Subidas publicas a galeria" on storage.objects;
drop policy if exists "Solo admin sube a galeria" on storage.objects;
create policy "Solo admin sube a galeria"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'gallery'
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);
